Pass all of config.my to Home Manager
This does not work, but needs to in order to avoid duplicating global
state like the username of the user you'll sign in as everyday.

    … while calling 'merge'

        at /nix/store/nn17kpb3mlp3kdhi4vm1m71w0m68f1gk-source/lib/types.nix:762:22:

        761|         check = x: isAttrs x || isFunction x || path.check x;
        762|         merge = loc: defs:
            |                      ^
        763|           (base.extendModules {

    error: The option `home-manager.users.jcf.my.system' does not exist. Definition values:
    - In `/nix/store/p6xn9czdx4w0zg4axh2k32gvra5357zq-source/nixos/common.nix':
        {
            zsh = {
            enable = true;
            };
        }